name: Push package
on:
  workflow_dispatch:

jobs:
  push:
    name: Push package
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v5

    - name: Pack and push
      run: |
        choco pack
        choco push --source=https://push.chocolatey.org/ --key="$Env:CHOCOLATEY_API_KEY"
      env:
        CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
