name: Push package
on:
  workflow_dispatch:

jobs:
  update:
    name: Update copyright year
    runs-on: windows-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Push package
      run: |
        choco pack
        choco push --source=https://push.chocolatey.org/ --key="$Env:CHOCOLATEY_API_KEY"
      env:
        CHOCOLATEY_API_KEY: ${{ secrets.CHOCOLATEY_API_KEY }}
